### ISSUE TITLE
useMart Timeout reached

### ISSUE THREAD

**Issue by rlittman16** [Huber-group-EMBL/biomaRt#25]
Hello, 

When using this function: 
 `human = useMart("ensembl",
         dataset = "hsapiens_gene_ensembl",
                 host = "uswest.ensembl.org")`

I get the following error:
Error in curl::curl_fetch_memory(url, handle = handle): Timeout was 
  reached: Resolving timed out after 10000 milliseconds

Thanks in advanced!

**Comment by grimbough** [comment]
It's likely that the Ensembl site is being slow, and this is intermittent.  You can try using `useEnsembl()` instead of `useMart()`.  It should try to use an alternative mirror if the first site it tries doesn't respond, which hopefully makes things easier for you.

**Comment by rlittman16** [comment]
Thanks! It may have been my connection as well. I got it to work on a server (not on my internet).

**Comment by corinabioinformatic** [comment]
hello! same problem again here (Europe) since yesterday:

`mart_any <- useMart("ensembl", version=versionEnsembl_raw , host = "https://www.ensembl.org")`
or
`listEnsembl()`

```
Ensembl site unresponsive, trying asia mirror
Ensembl site unresponsive, trying useast mirror
Error in .chooseEnsemblMirror(mirror = mirror, http_config = http_config) : 
  Unable to query any Ensembl site
```
