### ISSUE TITLE
R package providing query functionality to BioMart instances like Ensembl

### ISSUE THREAD

**Issue by crisprmax** [Huber-group-EMBL/biomaRt#27]
I keep running into this error when using biomaRt on Rstudio:

![image](https://user-images.githubusercontent.com/72586968/95533551-6e572b80-09b1-11eb-9a9e-abea79f3e68a.png)

Any suggestions?  Here's the code I used before:

![image](https://user-images.githubusercontent.com/72586968/95533613-98105280-09b1-11eb-9df2-3e7670298351.png)

Thank you!

**Comment by raphaelbetschart** [comment]
Do you have the newest version? Running "BiocManager::install('grimbough/biomaRt')" solved the problem for me.

**Comment by crisprmax** [comment]
Thank you raphaelbetschart, it was solved.
