### ISSUE TITLE
Error in UseMethod("filter_") : 

### ISSUE THREAD

**Issue by SunnyWit** [Huber-group-EMBL/biomaRt#38]
**There are my codes:**

library(biomaRt)
mart.snp.hs <- useMart(host="http://grch37.ensembl.org",                  
                       biomart = "ENSEMBL_MART_SNP",                
                       dataset = "hsapiens_snp")
res <- getBM(attributes = c( "refsnp_id","chr_name", "chrom_start", "chrom_end","allele"),     
             filters = list(chr_name=1,                    
                            start=c(222133118),                     
                            end=c(222204361)),      
             mart = mart.snp.hs)

**Then it shows errors:**

Error in UseMethod("filter_") : 
  "filter_"没有适用于"c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"目标对象的方法
此外: Warning messages:
1: `select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 

How can I solve this problem?
Thanks for you help!

**Comment by grimbough** [comment]
This is because the latest version of dplyr is incompatible with old version of BiocFileCache (and in turn biomaRt).  You'll need to update R & Biocondutor.  There's a bit more information in these threads:

https://support.bioconductor.org/p/p132704/#p132714
https://support.bioconductor.org/p/p132709/#p133220

**Comment by SunnyWit** [comment]
Thanks! I will try it
