### ISSUE TITLE
Possibility to set cache location

### ISSUE THREAD

**Issue by cruckert** [Huber-group-EMBL/biomaRt#45]
It would be nice to have the option to set the cache location. I am running getBM from apache web server as www-data user on Ubuntu. The home folder for www-data is /var/www which is not writeable for www-data by default so it cannot create the /var/www/.cache directory used by biomaRt.

**Comment by grimbough** [comment]
I don't think I've documented it, but you can use the environment variable `BIOMART_CACHE` to set the location of the cache.

I'll make a note to add some details to the vignette.

I guess not many people are using that if there's no documentation, so please let me know if you run into any issues.
